### ISSUE TITLE
How to bootstrap

### ISSUE THREAD

**Issue by majora2007** [Aguafrommars/Identity.Firebase#115]
Hello,

The samples are showing:
```
services.AddFirestoreStores(options =>
                {
                    Configuration.GetSection("AuthTokenOptions").Bind(options);
                })
 ```
however, after pulling from Nuget, all I can do is:
```
services.AddFirebaseClient(options =>
            {
                _config.GetSection("AuthTokenOptions").Bind(options);
            });
```

However, this signature is not correct, it's prompting for a tokenmanager. Any ideas what this means? I'm just trying to add this in as a drop in replacement for Identity.

**Comment by aguacongas** [comment]
You're not using the good lib I guess. There are [**Aguacongas.Identity.Firebase**](https://www.nuget.org/packages/Aguacongas.Identity.Firebase/) for [firebase DB](https://firebase.google.com/) and [**Aguacongas.Identity.Firestore**](https://www.nuget.org/packages/Aguacongas.Identity.Firestore/) for [firestore DB](https://firebase.google.com/docs/firestore/).  `AddFirestoreStores` is exposed by [**Aguacongas.Identity.Firestore**](https://www.nuget.org/packages/Aguacongas.Identity.Firestore/)

**Comment by majora2007** [comment]
Well I feel dumb, thanks for the quick reply.

**Comment by aguacongas** [comment]
There is no `DataContext` nor schema nor migration in noSQL DB.

**Comment by majora2007** [comment]
Ahh, so then EF with NoSQL isn't a thing and I need to use raw queries to interface with Firebase? 

Sorry if this is ruddiment, I'm new to .NET with NoSQL.

**Comment by aguacongas** [comment]
For firestore google provide [`Google.Cloud.Firestore`](https://www.nuget.org/packages/Google.Cloud.Firestore/)  
For firebase you can use my [FirebaseClient](https://github.com/Aguafrommars/Identity.Firebase/blob/master/src/Aguacongas.Firebase/FirebaseClient.cs) which use firebase WebAPI

**Comment by majora2007** [comment]
Thanks, I appreciate the help. Looks like I have a lot of work ahead of me to migrate off MySQL with EF Core.
